server:
  port: 8080

spring:
  application:
    name: proposals-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proposals}
    username: ${SPRING_DATASOURCE_USERNAME:proposals}
    password: ${SPRING_DATASOURCE_PASSWORD:proposals}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.btg.proposals.dto
        spring.json.value.default.type: com.btg.proposals.dto.proposal.ProposalEventDTO

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC:proposals.events}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  security:
    username: ${APP_SECURITY_USERNAME:admin}
    password: ${APP_SECURITY_PASSWORD:admin123}
  email:
    default-recipient: ${APP_EMAIL_DEFAULT_RECIPIENT:cliente@valorei.com.br}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

info:
  app:
    name: Proposals API
    description: POC de propostas de cartao de credito BTG
    version: 1.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
